// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter/index.vue')['default']
    AppMain: typeof import('./src/components/layout/AppMain/index.vue')['default']
    AppNavigation: typeof import('./src/components/layout/AppNavigation/index.vue')['default']
    Dynamic: typeof import('./src/components/layout/Dynamic.vue')['default']
    DynamicLayout: typeof import('./src/components/layout/DynamicLayout.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Static: typeof import('./src/components/layout/Static.vue')['default']
    StaticLayout: typeof import('./src/components/layout/StaticLayout.vue')['default']
    TextInput: typeof import('./src/components/common/TextInput/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
