// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter/index.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader/index.vue')['default']
    AppMain: typeof import('./src/components/layout/AppMain/index.vue')['default']
    AppNavigation: typeof import('./src/components/layout/AppNavigation/index.vue')['default']
    DynamicLayout: typeof import('./src/components/layout/DynamicLayout.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaticLayout: typeof import('./src/components/layout/StaticLayout.vue')['default']
    TextInput: typeof import('./src/components/common/TextInput/index.vue')['default']
  }
}
